#!/bin/bash

set -euo pipefail

qsmac_check_os() {
  if ! [[ "$OSTYPE" =~ darwin* ]]; then
      echo "This is meant to be run on macOS only"
      exit
  fi
}

qsmac_check_brew() {
  if ! command -v brew > /dev/null; then
      echo "Homebrew not installed!"
      echo "In order to use this script please install homebrew from https://brew.sh"
      exit
  fi
}

qsmac_check_dirs() {
    result=0

    for dir in /usr/local/bin /usr/local/sbin; do
        if [[ ! -d $dir || ! -w $dir ]]; then
            echo "$dir must exist and be writeable"
            result=1
        fi
    done

    return $result
}

qsmac_add_config() {
	
    homebrew_bash=/usr/local/opt/bash/bin/bash
    if [ -f $homebrew_bash ]; then
        # Offer to change shell to newly installed bash
        read -p "Do you want to change your shell to the latest bash (Y/N)? " -n 1 -r
        if [[ $REPLY =~ [Yy]$ ]]; then
            grep -qF "$homebrew_bash" /etc/shells || echo "$homebrew_bash" | sudo tee -a /etc/shells > /dev/null
            echo # Blank line so the password entry isn't bunched-up
            chsh -s $homebrew_bash
            echo "shell changed to $homebrew_bash"
        else
            echo # Blank line
            echo "OK, leaving your shell as $SHELL"
        fi
    fi

    # gdb requires special privileges to access Mach ports.
    # One can either codesign the binary as per https://sourceware.org/gdb/wiki/BuildingOnDarwin
    # Or, on 10.12 Sierra or later with SIP, declare `set startup-with-shell off` in `~/.gdbinit`:    
    gdb_init=$HOME/.gdbinit
    if [ -f /usr/local/opt/gdb/bin/gdb ]; then
        grep -qF 'set startup-with-shell off' $gdb_init || echo 'set startup-with-shell off' | tee -a $gdb_init > /dev/null
        echo "Added or modified $gdb_init"
    fi

    # Make changes to PATH/MANPATH/INFOPATH/LDFLAGS/CPPFLAGS
	qsmac_config=$HOME/.qsmac
	if [ ! -f $qsmac_config ]; then
    	cp .qsmac $qsmac_config
		echo "Added $qsmac_config"
	fi

	
	if [  -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
	    # Offer to add qsmac config to zsh shell profile
	    read -p "Do you want to add qsmac config to your zsh shell profile (Y/N)? " -n 1 -r
	    if [[ $REPLY =~ [Yy]$ ]]; then
			echo # Blank line
			
			# Check if .zprofile exists
			shell_profile=$HOME/.zprofile
			if [ ! -f $shell_profile ]
			then
			    touch $shell_profile
				echo 'Added $shell_profile'
			fi
	
			echo '# include .qsmac if it exists' >> $shell_profile
			echo 'if [ -f $HOME/.qsmac ]; then' >> $shell_profile
		    echo '	. $HOME/.qsmac' >> $shell_profile
			echo 'fi' >> $shell_profile
			
			echo 'Your shell profile was configured succesfully!'
	    else
			echo "Remember to add '. ~/.qsmac' to your ~/.zprofile, ~/.zshrc or your shell's equivalent config file"
	    fi
	elif [ -n "`$SHELL -c 'echo $BASH_VERSION'`" ]; then
	    # Offer to add qsmac config to zsh shell profile
	    read -p "Do you want to add qsmac config to your bash shell profile (Y/N)? " -n 1 -r
	    if [[ $REPLY =~ [Yy]$ ]]; then
			echo # Blank line
			
			# Check if .zprofile exists
			shell_profile=$HOME/.bash_profile
			if [ ! -f $shell_profile ]
			then
			    touch $shell_profile
				echo 'Added $shell_profile'
			fi
	
			echo '# include .qsmac if it exists' >> $shell_profile
			echo 'if [ -f $HOME/.qsmac ]; then' >> $shell_profile
		    echo '	. $HOME/.qsmac' >> $shell_profile
			echo 'fi' >> $shell_profile
			
			echo 'Your shell profile was configured succesfully!'
	    else
			echo "Remember to add '. ~/.qsmac' to your ~/.bash_profile, ~/.bashrc or your shell's equivalent config file"
	    fi
	else
	    echo "Remember to add '. ~/.qsmac' to your shell's equivalent config file"
	fi
 
}

qsmac_formulas=(
    # GNU programs non-existing in macOS
    "watch"
    "wget"
    "wdiff"
    "gdb"
    "autoconf"

    # GNU programs whose BSD counterpart is installed in macOS
    "coreutils"
    "binutils"
    "diffutils"
    "ed"
    "findutils"
    "gawk"
    "gnu-indent"
    "gnu-sed"
    "gnu-tar"
    "gnu-which"
    "grep"
    "gzip"
    "screen"

    # GNU programs existing in macOS which are outdated
    "bash"
    "emacs"
    "gpatch"
    "less"
    "m4"
    "make"
    "nano"
    "bison"

    # BSD programs existing in macOS which are outdated
    "flex"

    # Other common/preferred programs in GNU/Linux distributions
    "libressl"
    "file-formula"
    "git"
    "openssh"
    "perl"
    "python"
    "rsync"
    "unzip"
    "vim"
)

qsmac_install() {
    qsmac_check_os;
    qsmac_check_brew;
    qsmac_check_dirs;

    # Install all formulas
    for (( i=0; i<${#qsmac_formulas[@]}; i++ )); do
        if ! brew ls --versions ${qsmac_formulas[i]} > /dev/null; then
            brew install ${qsmac_formulas[i]}
        fi
    done

	qsmac_add_config;
}

qsmac_uninstall() {
    qsmac_check_os;
    qsmac_check_brew;

    # Remove gdb fix
    sed -i.bak '/set startup-with-shell off/d' ~/.gdbinit && rm ~/.gdbinit.bak

    # Offer to change default shell back to macOS default
    bash_is_local=false
    if [[ $SHELL =~ local ]]; then
        read -p "Do you want to change your shell back to macOS default (macOSVersion >= 10.15.x ? zsh : bash) ? " -n 1 -r
        if [[ $REPLY =~ [Yy]$ ]]; then
            sudo sed -i.bak '/\/usr\/local\/bin\/bash/d' /etc/shells && sudo rm /etc/shells.bak
            echo
            if [[ $(sw_vers -productVersion | awk -F. '{print $2}') -gt 14 ]]; then
                chsh -s /bin/zsh
            else
                chsh -s /bin/bash
            fi
        else
            echo "OK, leaving your shell as $SHELL"
            if [[ $SHELL == /usr/bin/local/bash ]]; then
                bash_is_local=true
            fi
        fi
    fi

    # Uninstall all formulas in reverse order
    for (( i=${#qsmac_formulas[@]}-1; i>=0; i-- )); do
        if [[ ${qsmac_formulas[i]} != bash ]]; then
            brew uninstall -f $(echo "${qsmac_formulas[i]}" | cut -d ' ' -f1)
        fi
    done
    
    # Only remove bash if the user didn't elect to keep it as their shell
    if [[ "$bash_is_local" != true ]]; then
        brew uninstall bash
    fi

    # Remove changes to PATH/MANPATH/INFOPATH/LDFLAGS/CPPFLAGS
    rm -f ~/.qsmac
    echo "Remove '. ~/.qsmac' from your ~/.bashrc, ~/.zshrc or your shell's equivalent config file"
}

qsmac_info() {
    qsmac_check_os;
    qsmac_check_brew;

    for (( i=0; i<${#qsmac_formulas[@]}; i++ )); do
        brew info $(echo "${qsmac_formulas[i]}" | cut -d ' ' -f1)
        printf "\n\n===============================================================================================================================\n\n"
    done
}

qsmac_help() {
  echo "usage: qsmac [-h] [command]";
  echo ""
  echo "valid commands:"
  echo "  install    install GNU/Linux utilities"
  echo "  uninstall  uninstall GNU/Linux utilities"
  echo "  info       show info on GNU/Linux utilities"
  echo "  config     add qsmac to shell config file"
  echo ""
  echo "optional arguments:"
  echo "  -h, --help  show this help message and exit"
}

qsmac_main() {
    if [ $# -eq 1 ]; then
        case $1 in
            "install") qsmac_install ;;
            "uninstall") qsmac_uninstall ;;
            "info") qsmac_info ;;
			"config") qsmac_add_config ;;
            "-h") qsmac_help ;;
            "--help") qsmac_help ;;
        esac
    else
        qsmac_help;
        exit
    fi
}

qsmac_main "$@"